### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by DezorianGuv** [DevRico003/KinskiGPT#1]
I am new to streamlit so I do not understand how to use the "streamlit run main.py" command, as streamlit isn't present within the root folder of the cloned repository. I tried use"python /path/to/streamlit run main.py", but doesn't seem to work either.

What am I doing wrong?

**Comment by DevRico003** [comment]
steps to do:

1. clone repo:
```bash
git clone https://github.com/DevRico003/KinskiGPT.git
```
2. go into the cloned directory:
```bash
cd KinskiGPT
```
3. install requirements:
```bash
pip install -r requirements.txt
```
4. Create a `.env` file in the root directory of the project (inside KinskiGPT folder). Inside this file, set the following variable:
```bash
OPENAI_API_KEY=<Your_OpenAI_API_Key>
```
5. start the app:
```bash
streamlit run main.py
```

**Comment by DezorianGuv** [comment]
![Screenshot 2024-02-08 161150](https://github.com/DevRico003/KinskiGPT/assets/89683077/0ffbd1e1-e799-42e8-bdc8-d67b639fa546)

**Comment by DezorianGuv** [comment]
There is no streamlit present within the folder, so I'd assume that it cannot be executed from here, right?

**Comment by DevRico003** [comment]
streamlit is in the requirements.txt. You install streamlit with the python package manager pip.

```bash
pip install -r requirements.txt
```

there is no folder for streamlit because it needs to be on your system.

follow the steps that i have given you and it should work.

**Comment by DevRico003** [comment]
python3 and pip needs to be installed as prerequisite

**Comment by DezorianGuv** [comment]
Python3.10 and pip are installed as I am using software like StableDiffusion. 

I also tried (within cmd) to update streamlit with "python -m pip install -U Streamlit" or "pip install streamlit" but I get severla messages stating"requirement already statisfied". Yet, when I want to check the streamlit version with "streamlit --version", I again get the message that the command streamlit may contain a typo or cannot be found. Weird, I can use the the commands "python" and "pip", but not "streamlit" somehow.

![Screenshot 2024-02-08 162754](https://github.com/DevRico003/KinskiGPT/assets/89683077/166d007f-3d2c-4885-9173-f95e7830e795)

**Comment by DevRico003** [comment]
The issue you are encountering appears to be related to the Streamlit installation on your system. The fact that you can run `python` and `pip` but not `streamlit` suggests that the Streamlit command is not in your system's PATH, or it was not installed correctly.

Here are some steps you can take to troubleshoot and resolve the issue:

1. **Check if Streamlit is installed in your Python environment**:
   - Open a command prompt and type `python -m streamlit --version`. This will bypass any PATH issues and attempt to run Streamlit using your Python interpreter.

2. **Ensure Streamlit is installed in the correct Python environment**:
   - If you have multiple Python installations, Streamlit might be installed in a different one. Make sure you activate the correct environment before running the `pip install streamlit` command.

3. **Check your PATH environment variable**:
   - On Windows, the PATH environment variable allows the system to locate executables. If Streamlit was installed but is not in the PATH, you will not be able to run it directly from the command prompt.
   - You can check which directories are included in your PATH by running `echo %PATH%` in the command prompt.

4. **Add Streamlit to your PATH manually**:
   - Find out where Streamlit was installed by running `python -m site --user-site` to show the user site-packages directory. Streamlit’s executable should be in a `Scripts` directory within this directory.
   - Add the path to the `Scripts` directory to your system's PATH environment variable.

5. **Use a Virtual Environment**:
   - Sometimes, using a Python virtual environment can help resolve these issues. You can create a virtual environment in your project directory by running `python -m venv myenv` and then activate it with `myenv\Scripts\activate`. After activation, try installing Streamlit again within this environment.

6. **Reinstall Streamlit**:
   - You can try to uninstall and then reinstall Streamlit. Use the commands `pip uninstall streamlit` followed by `pip install streamlit`.

Try these steps and see if they resolve your issue. If you can run `python -m streamlit --version` successfully, you can use that as a temporary workaround to run Streamlit by replacing `streamlit` with `python -m streamlit` in your commands.

If all these steps would not work, try with wsl (windows subsystem for linux) with ubuntu.

**Comment by DevRico003** [comment]
do not forget to insert your api key from openai in your .env, after fixing the streamlit issue.

**Comment by DezorianGuv** [comment]
I am getting closer to solving this. I edit the PATH: 

> It seems like you have correctly identified the issue related to the PATH environment variable not including the directory where Streamlit executable (streamlit.exe) is located. Here's what you can do to fix it:
> 
> Add Streamlit directory to PATH manually:
> 
> Open File Explorer and navigate to the following directory:
> C:\Users\fires\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts
> Copy the path of the Scripts directory.
> Press Win + R to open the Run dialog, type sysdm.cpl, and hit Enter to open System Properties.
> Go to the "Advanced" tab and click on the "Environment Variables" button.
> In the "System Variables" section, select the Path variable and click on the "Edit" button.
> Click on the "New" button and paste the path you copied earlier.
> Click "OK" to save the changes and close all windows.
> Verify the PATH variable:
> 
> Open a new command prompt window and type streamlit --version to verify that Streamlit is now recognized as a command.
> You should see the version information printed on the screen without any errors.
> By following these steps, you should be able to add the Streamlit directory to your system's PATH variable and access the Streamlit command from any command prompt window without issues.

So, I edited my API.env file to add my openani API key (that I freshly generated) and then started the "streamlit run main.py" command and a chatbox opened within my browser. But once I typed in anything, I get the following message:

> "You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
> You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
> Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
> A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742"

**Comment by DevRico003** [comment]
This error comes, because the app needs to use an older version of openai.

To use a new Python environment to install specific packages, you can use virtual environments which are a feature of Python used to maintain dependencies for different projects. Below are the steps you can take to set up a new virtual environment, activate it, and install the packages `openai==0.27.7`, `streamlit`, and `python-dotenv`. 

1. **Create a Virtual Environment**:
   - Open a command prompt or terminal window.
   - Navigate to your project directory where you want the virtual environment to be set up.
   - Run the following command to create a virtual environment named `env` (you can name it whatever you like):

   ```bash
   python -m venv env
   ```

2. **Activate the Virtual Environment**:

   ```bash
   env\Scripts\activate.bat
   ```

   When the virtual environment is activated, your command prompt will usually show the name of the environment in parentheses.

4. **Install the Packages**:
   - With the virtual environment activated, install the specific version of the `openai` package, `streamlit`, and `python-dotenv` using `pip`:

   ```bash
   pip install openai==0.27.7 streamlit python-dotenv
   ```

   This command will download and install the specified version of the `openai` library along with the latest versions of `streamlit` and `python-dotenv` that are compatible with it.

5. **Verify Installation**:
   - To ensure that the packages are installed correctly, you can check their versions:

   ```bash
   python -m pip show openai
   streamlit --version
   python -m pip show python-dotenv
   ```

6. **Deactivate the Virtual Environment**:
   - When you're done working in the virtual environment, you can deactivate it by running:

   ```bash
   deactivate
   ```

Remember, every time you want to work on your project, you should navigate to your project directory and activate your virtual environment with the `activate` command. This ensures that you are using the correct Python interpreter and dependencies for your project.

**Comment by DezorianGuv** [comment]
I did all the steps. I verified my installations as you can see. What could be still the problem?

![Screenshot 2024-02-09 174433](https://github.com/DevRico003/KinskiGPT/assets/89683077/40f2cffb-86c5-4464-9504-1cea53f473af)

**Comment by DevRico003** [comment]
You did not installed the needed openai version. The version you installed is to new, there was a major change in there Api. As mentioned before, you need to install an older version of openai. Please, install openai==0.27.7
